name: 💡 Feature Request
description: Suggest a new feature or improvement for D8 Progress
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We love hearing ideas from our community.
        
        💡 **Tip**: Before submitting, please search existing issues and discussions to avoid duplicates.
        
        🧠 **Remember**: D8 Progress is designed specifically for neurodivergent minds. Consider how your suggestion fits this focus!

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: |
        A clear description of the problem you're facing or the need you have.
        Example: "I'm frustrated when..." or "It would be helpful if..."
      placeholder: Describe the problem or need...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What would you like to see?
      description: A clear description of what you want to happen
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: This would help users who...
      description: Which type of users would benefit most?
      multiple: true
      options:
        - Have ADHD
        - Are autistic
        - Use minimal gamification
        - Use full gamification
        - Are new to the app
        - Are power users
        - Use assistive technology
        - All users
        - Other (please specify below)

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      description: Help us understand the impact
      options:
        - "Critical - I can't use the app effectively without this"
        - "High - This would significantly improve my experience"
        - "Medium - This would be a nice improvement"
        - "Low - This would be cool to have someday"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: What alternatives have you considered?
      description: |
        Have you thought of other ways to solve this problem?
        Are you currently using any workarounds?
      placeholder: Describe any alternative solutions or workarounds...

  - type: textarea
    id: examples
    attributes:
      label: Examples or mockups
      description: |
        If you have examples from other apps, mockups, or specific ideas about how this should work,
        please share them here. Images welcome!
      placeholder: Share examples, mockups, or detailed descriptions...

  - type: checkboxes
    id: gamification
    attributes:
      label: Gamification considerations
      description: How should this feature work with different gamification modes? (Check all that apply)
      options:
        - label: Should work the same in all gamification modes
        - label: Should have different behavior in Party Mode vs Lite Mode
        - label: Should be optional/configurable per user
        - label: Only relevant for certain gamification modes
        - label: Not applicable to gamification

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: |
        Add any other context, screenshots, or information about the feature request here.
        
        Consider:
        - How does this relate to neurodivergent experiences?
        - Would this work well with executive dysfunction?
        - How might this impact users with different needs?
      placeholder: Any additional context...

  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions to make sure this isn't a duplicate
          required: true
        - label: I have explained the problem this would solve, not just the solution I want
          required: true